
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE SCHEMA IF NOT EXISTS "staging";

ALTER SCHEMA "staging" OWNER TO "postgres";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."pft_role" AS ENUM (
    'student',
    'teacher'
);

ALTER TYPE "public"."pft_role" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."ClassStudentMapping" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "classId" bigint NOT NULL,
    "studentId" "text" NOT NULL,
    "studentEmail" "text" NOT NULL
);

ALTER TABLE "public"."ClassStudentMapping" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."SchoolClass" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "teacherId" "text" NOT NULL,
    "classCode" "text" NOT NULL,
    "className" "text" NOT NULL
);

ALTER TABLE "public"."SchoolClass" OWNER TO "postgres";

ALTER TABLE "public"."SchoolClass" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SchoolClass_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."ClassStudentMapping"
    ADD CONSTRAINT "ClassStudentMapping_pkey" PRIMARY KEY ("classId", "studentId");

ALTER TABLE ONLY "public"."SchoolClass"
    ADD CONSTRAINT "SECTION_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."SchoolClass"
    ADD CONSTRAINT "SchoolClass_classCode_key" UNIQUE ("classCode");

ALTER TABLE ONLY "public"."ClassStudentMapping"
    ADD CONSTRAINT "ClassStudentMapping_classId_fkey" FOREIGN KEY ("classId") REFERENCES "public"."SchoolClass"("id");

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."ClassStudentMapping" TO "anon";
GRANT ALL ON TABLE "public"."ClassStudentMapping" TO "authenticated";
GRANT ALL ON TABLE "public"."ClassStudentMapping" TO "service_role";

GRANT ALL ON TABLE "public"."SchoolClass" TO "anon";
GRANT ALL ON TABLE "public"."SchoolClass" TO "authenticated";
GRANT ALL ON TABLE "public"."SchoolClass" TO "service_role";

GRANT ALL ON SEQUENCE "public"."SchoolClass_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SchoolClass_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SchoolClass_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;

--
-- Dumped schema changes for auth and storage
--

